services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.4
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  api:
    restart: always
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile dev
      context: ./
    ports:
      - 7777:3000
    volumes:
      - /home/node/app/node_modules
      - ./:/home/node/app
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DB_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  migration:
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile migration
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DB_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}